### ISSUE TITLE
/library_demo/dashboard 500 error

### ISSUE THREAD

**Issue by zhangchunlin** [uliwebext/uliweb-peafowl#2]
in uliweb-peafowl-demo access http://localhost:8000/library_demo/dashboard can get this error
```
[ERROR [29348] root 2018-02-09 14:06:05,606 /home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py,891] 'NoneType' object has no attribute 'layout'
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1450, in _open
    response = self.call_view(mod, handler_cls, handler, req, res, kwargs=values)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 993, in call_view
    result = self.call_handler(handler, request, response, env, wrap, args, kwargs)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1104, in call_handler
    result = self._call_function(handler, request, response, env, args, kwargs)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1097, in _call_function
    result = handler(*args, **kwargs)
  File "/home/zhangclb/sandbox/uliweb/opt/uliweb-peafowl/uliweb_peafowl/library_demo/views_dashboard.py", line 21, in index
    view = self.instance.get_view()
  File "/home/zhangclb/sandbox/uliweb/opt/uliweb-peafowl/uliweb_peafowl/dashboard/common.py", line 95, in get_view
    'digital': self.get_digital_panes(),
  File "/home/zhangclb/sandbox/uliweb/opt/uliweb-peafowl/uliweb_peafowl/dashboard/common.py", line 88, in get_digital_panes
    return self._get_sorted_panels(self.digital_name)
  File "/home/zhangclb/sandbox/uliweb/opt/uliweb-peafowl/uliweb_peafowl/dashboard/common.py", line 48, in _get_sorted_panels
    layout = self._get_layout(dashboardname).split('-')
  File "/home/zhangclb/sandbox/uliweb/opt/uliweb-peafowl/uliweb_peafowl/dashboard/common.py", line 40, in _get_layout
    return panellayout.layout
AttributeError: 'NoneType' object has no attribute 'layout'
```

**Comment by limodou** [comment]
This demo is not finished in repo.
